"""Render the original vector animation, captions, and soundtrack.

No provider API calls or external artwork are used. Speech is generated by
synthesize.ps1. Requires Pillow, numpy, and imageio-ffmpeg (see README.md).
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import os
from pathlib import Path
import re
import subprocess
import sys
import textwrap
import wave

import numpy as np
from PIL import Image, ImageDraw, ImageFont

BASE = Path(__file__).resolve().parent
ROOT = BASE.parent
TIMELINE = json.loads((BASE / "timeline.json").read_text(encoding="utf-8"))
DURATION = TIMELINE["duration"]
FPS = 24
SCALE = 1.5
WIDTH, HEIGHT = 1920, 1080
SR = 44100
OUT = BASE / "deliverables"
OUT.mkdir(exist_ok=True)

INK = "#0a1022"
WHITE = "#f2f1ff"
MUTED = "#a6b2cf"
TEAL = "#5aefd0"
PINK = "#ff7ca8"
GOLD = "#ffda8b"
BLUE = "#80a7ff"
PANEL = "#111a31"
FONTROOT = Path(os.environ.get("WINDIR", "C:/Windows")) / "Fonts"
FONTFILES = {"normal": "segoeui.ttf", "bold": "segoeuib.ttf", "light": "segoeuil.ttf", "italic": "segoeuii.ttf", "mono": "consola.ttf"}
FONTS = {}

with (ROOT / "outputs/dta_structured_state_2026-09-30/abstract_filter_metrics.csv").open(newline="", encoding="utf-8") as f:
    REVIEWS = [r for r in csv.DictReader(f) if r["dataset"] == "rerun_abstract_available"]
assert len(REVIEWS) == 8
assert sum(int(r["total_records"]) for r in REVIEWS) == 26832
assert round(sum(float(r["WSS@95"]) for r in REVIEWS) / 8, 3) == 0.661


def font(size, style="normal"):
    key = (round(size * SCALE), style)
    if key not in FONTS:
        FONTS[key] = ImageFont.truetype(str(FONTROOT / FONTFILES[style]), key[0])
    return FONTS[key]


def clamp(x, lo=0, hi=1):
    return min(hi, max(lo, x))


def smooth(x):
    x = clamp(x)
    return x * x * (3 - 2 * x)


def wrap_words(text, size, width, style="normal"):
    result, line = [], ""
    for word in text.split():
        candidate = f"{line} {word}".strip()
        if font(size, style).getlength(candidate) > width * SCALE and line:
            result.append(line)
            line = word
        else:
            line = candidate
    if line:
        result.append(line)
    return result


class Canvas:
    def __init__(self, im):
        self.im = im
        self.d = ImageDraw.Draw(im)

    def box(self, xy, fill, outline=None, radius=0, width=1):
        q = tuple(round(v * SCALE) for v in xy)
        if radius:
            self.d.rounded_rectangle(q, radius=round(radius * SCALE), fill=fill, outline=outline, width=max(1, round(width * SCALE)))
        else:
            self.d.rectangle(q, fill=fill, outline=outline, width=max(1, round(width * SCALE)))

    def line(self, points, fill, width=1):
        self.d.line([(round(x * SCALE), round(y * SCALE)) for x, y in points], fill=fill, width=max(1, round(width * SCALE)), joint="curve")

    def poly(self, points, fill, outline=None):
        self.d.polygon([(round(x * SCALE), round(y * SCALE)) for x, y in points], fill=fill, outline=outline)

    def ellipse(self, xy, fill, outline=None, width=1):
        self.d.ellipse(tuple(round(v * SCALE) for v in xy), fill=fill, outline=outline, width=max(1, round(width * SCALE)))

    def txt(self, xy, text, size=24, fill=WHITE, style="normal", anchor="lt", maxwidth=None):
        if maxwidth:
            while font(size, style).getlength(text) > maxwidth * SCALE and size > 10:
                size -= 0.5
        self.d.text(tuple(round(v * SCALE) for v in xy), text, font=font(size, style), fill=fill, anchor=anchor)

    def paragraph(self, xy, text, size=24, fill=MUTED, width=500, style="normal", leading=1.28):
        lines = wrap_words(text, size, width, style)
        for i, line in enumerate(lines):
            self.txt((xy[0], xy[1] + i * size * leading), line, size, fill, style)
        return len(lines) * size * leading

    def pill(self, x, y, text, color=TEAL, size=15, width=None):
        width = width or font(size, "bold").getlength(text) / SCALE + 28
        self.box((x, y, x + width, y + size + 17), PANEL, color, 8)
        self.txt((x + 14, y + 7), text, size, color, "bold")

    def arrow(self, a, b, color=TEAL, width=3):
        self.line([a, b], color, width)
        angle = math.atan2(b[1] - a[1], b[0] - a[0])
        self.poly([b, (b[0] - 11 * math.cos(angle - 0.5), b[1] - 11 * math.sin(angle - 0.5)), (b[0] - 11 * math.cos(angle + 0.5), b[1] - 11 * math.sin(angle + 0.5))], color)


def make_background():
    y, x = np.mgrid[0:HEIGHT, 0:WIDTH]
    a = np.exp(-((x - WIDTH * .75) ** 2 / (WIDTH * .52) ** 2 + (y - HEIGHT * .32) ** 2 / (HEIGHT * .48) ** 2))
    b = np.exp(-((x - WIDTH * .13) ** 2 / (WIDTH * .40) ** 2 + (y - HEIGHT * .65) ** 2 / (HEIGHT * .42) ** 2))
    rgb = np.zeros((HEIGHT, WIDTH, 3), dtype=np.uint8)
    for i, (base, av, bv) in enumerate([(7, 13, 5), (11, 5, 13), (25, 23, 15)]):
        rgb[:, :, i] = base + a * av + b * bv
    im = Image.fromarray(rgb)
    c = Canvas(im)
    c.box((0, 565, 1280, 720), "#0b1020")
    for i in range(-7, 16):
        c.line([(640 + i * 76, 565), (640 + i * 150, 720)], "#19233a")
    for y0 in [577, 602, 638, 688]:
        c.line([(0, y0), (1280, y0)], "#19233a")
    for x0 in [55, 420, 930, 1230]:
        c.line([(x0, 0), (x0, 565)], "#182039")
    return im


BG = make_background()


def shadow(c, x, y, w=80):
    c.ellipse((x-w/2, y-6, x+w/2, y+6), "#050914")


def librarian(c, x, y, s=1, t=0, pose="clipboard"):
    def p(a, b):
        return x+a*s, y+b*s
    def rect(q, fill, radius=0, outline=None):
        c.box((*p(q[0],q[1]), *p(q[2],q[3])), fill, outline, radius*s)
    def ell(q, fill, outline=None, width=1):
        c.ellipse((*p(q[0],q[1]), *p(q[2],q[3])), fill, outline, width*s)
    shadow(c, x, y, 97*s)
    # Shoes, trousers, jacket: an exhausted but immaculate club owner.
    rect((-28,-48,-5,-6), "#11182e", 4)
    rect((7,-48,29,-6), "#11182e", 4)
    rect((-34,-9,-2,0), "#65728d", 3)
    rect((3,-9,37,0), "#65728d", 3)
    rect((-39,-111,39,-39), "#7b325c", 13)
    c.poly([p(-15,-107),p(15,-107),p(6,-55),p(-5,-55)], "#1a2035")
    rect((-10,-120,10,-101), "#b47d62", 4)
    ell((-28,-171,29,-116), "#c99576")
    ell((-30,-176,30,-144), "#c4c9d6")
    ell((17,-184,41,-159), "#c4c9d6")
    rect((-30,-164,-18,-136), "#c4c9d6", 5)
    rect((-24,-150,-3,-134), "#28324b", 5, TEAL)
    rect((4,-150,26,-134), "#28324b", 5, TEAL)
    c.line([p(-3,-143),p(4,-143)], TEAL, 2*s)
    blink = math.sin(t*1.7) > .994
    if not blink:
        ell((-17,-144,-12,-138), WHITE)
        ell((11,-144,16,-138), WHITE)
    c.line([p(-20,-156),p(-7,-158)], "#32384b", 2*s)
    c.line([p(9,-158),p(22,-154)], "#32384b", 2*s)
    talking = any(a["speaker"] == "Librarian" and a["start"] <= t < a["end"] for a in CAPTIONS)
    if talking and math.sin(t*15) > -.2:
        ell((-5,-130,10,-120), "#6d3b44")
    else:
        c.line([p(-6,-123),p(10,-124)], "#6d3b44", 2*s)
    if pose == "keys":
        c.line([p(32,-97),p(63,-105),p(78,-126)], "#7b325c", 14*s)
        ell((73,-134,86,-121), "#c99576")
        ell((79,-126,94,-110), None, GOLD, 3)
        for i in range(3):
            c.line([p(86+i*4,-111),p(85+i*4,-90)], GOLD, 3*s)
            c.line([p(85+i*4,-95),p(89+i*4,-95)], GOLD, 2*s)
    else:
        c.line([p(32,-93),p(44,-70),p(23,-65)], "#7b325c", 13*s)
        rect((6,-89,36,-51), "#d6c29e", 3)
        rect((16,-93,26,-86), "#7c8393", 2)
        for yy in [-79,-72,-65]:
            c.line([p(12,yy),p(30,yy)], "#736552", 1*s)
    c.line([p(-32,-95),p(-44,-68),p(-35,-53)], "#7b325c", 13*s)
    ell((-41,-60,-27,-46), "#c99576")


def paper(c, x, y, t=0, s=1, accent=BLUE, label="ABSTRACT", worried=False):
    yy = y + math.sin(t*2+x*.05)*3*s
    w,h=54*s,78*s
    shadow(c,x, y+13*s,65*s)
    c.line([(x-12*s,yy+h*.45),(x-15*s,yy+h*.65)], "#c4cbe0", 3*s)
    c.line([(x+11*s,yy+h*.45),(x+15*s,yy+h*.65)], "#c4cbe0", 3*s)
    c.box((x-w/2,yy-h/2,x+w/2,yy+h/2), "#e4e7f3", radius=5*s)
    c.poly([(x+w/2-13*s,yy-h/2),(x+w/2,yy-h/2+13*s),(x+w/2-13*s,yy-h/2+13*s)], accent)
    c.txt((x-w/2+5*s,yy-h/2+8*s),label,7*s,INK,"bold",maxwidth=w-10*s)
    for j in range(3):
        c.line([(x-w/2+7*s,yy-h/2+(23+j*7)*s),(x+w/2-(8+j*4)*s,yy-h/2+(23+j*7)*s)],"#95a2bc",1*s)
    c.ellipse((x-12*s,yy+10*s,x-8*s,yy+15*s),INK)
    c.ellipse((x+8*s,yy+10*s,x+12*s,yy+15*s),INK)
    talking = any(a["speaker"] == "Paper" and a["start"] <= t < a["end"] for a in CAPTIONS)
    if talking and math.sin(t*17) > -.2:
        c.ellipse((x-5*s,yy+19*s,x+5*s,yy+27*s),INK)
    else:
        c.line([(x-4*s,yy+24*s),(x+4*s,yy+(22 if worried else 24)*s)],INK,1*s)


def robot(c, x, y, t=0, s=1, output=False):
    shadow(c,x,y,92*s)
    # A folding stool: its one extravagance.
    c.line([(x-23*s,y-4*s),(x+24*s,y-39*s)],"#8194b4",3*s)
    c.line([(x+23*s,y-4*s),(x-24*s,y-39*s)],"#8194b4",3*s)
    c.box((x-34*s,y-43*s,x+34*s,y-36*s),"#9eacc4",radius=3*s)
    bob=math.sin(t*2.4)*2*s
    c.box((x-33*s,y-100*s+bob,x+33*s,y-45*s+bob),"#398d83",TEAL,10*s,2)
    c.box((x-24*s,y-89*s+bob,x+24*s,y-66*s+bob),"#102c35",radius=5*s)
    c.ellipse((x-16*s,y-82*s+bob,x-10*s,y-75*s+bob),TEAL)
    c.ellipse((x+10*s,y-82*s+bob,x+16*s,y-75*s+bob),TEAL)
    c.txt((x,y-61*s+bob),"JEV",10*s,TEAL,"bold","mt")
    c.line([(x,y-100*s+bob),(x,y-112*s+bob)],TEAL,2*s)
    c.ellipse((x-4*s,y-119*s+bob,x+4*s,y-111*s+bob),GOLD)
    c.line([(x-32*s,y-77*s+bob),(x-47*s,y-63*s+bob)],TEAL,4*s)
    c.line([(x+32*s,y-77*s+bob),(x+47*s,y-63*s+bob)],TEAL,4*s)
    if output:
        c.box((x+35*s,y-159*s,x+185*s,y-111*s),PANEL,TEAL,7*s)
        c.txt((x+47*s,y-150*s),"p(retain) = 0.87",13*s,TEAL,"mono")
        c.txt((x+47*s,y-130*s),"ILLUSTRATIVE OUTPUT",7*s,MUTED,"bold")


def llm(c,x,y,t=0,s=1,color=PINK,name="LLM"):
    shadow(c,x,y,90*s)
    c.box((x-24*s,y-63*s,x-5*s,y-5*s),"#322446",radius=3*s)
    c.box((x+5*s,y-63*s,x+24*s,y-5*s),"#322446",radius=3*s)
    c.box((x-30*s,y-9*s,x-3*s,y),color,radius=3*s)
    c.box((x+2*s,y-9*s,x+33*s,y),color,radius=3*s)
    c.box((x-39*s,y-133*s,x+39*s,y-49*s),color,radius=11*s)
    c.poly([(x-15*s,y-133*s),(x+15*s,y-133*s),(x,y-70*s)],"#dfe6f8")
    c.poly([(x,y-122*s),(x-6*s,y-95*s),(x,y-81*s),(x+6*s,y-95*s)],INK)
    c.ellipse((x-29*s,y-196*s,x+29*s,y-139*s),"#dfb7a0")
    c.box((x-31*s,y-185*s,x+31*s,y-175*s),"#2b233a",radius=4*s)
    c.box((x-25*s,y-171*s,x-2*s,y-156*s),INK,radius=4*s)
    c.box((x+2*s,y-171*s,x+25*s,y-156*s),INK,radius=4*s)
    c.line([(x-3*s,y-164*s),(x+4*s,y-164*s)],INK,2*s)
    talking = any(a["speaker"] == "LLM" and a["start"] <= t < a["end"] for a in CAPTIONS)
    if talking and math.sin(t*16) > -.2:
        c.ellipse((x-8*s,y-153*s,x+8*s,y-141*s),"#76483e")
    else:
        c.line([(x-10*s,y-147*s),(x+10*s,y-147*s)],"#76483e",2*s)
    c.line([(x-33*s,y-120*s),(x-58*s,y-87*s)],color,14*s)
    c.line([(x+33*s,y-120*s),(x+58*s,y-92*s)],color,14*s)
    c.pill(x-38*s,y-43*s,name,WHITE,size=10*s,width=76*s)


def chrome(c,scene,t):
    c.txt((42,24),"CLUB ELIGIBILITY",15,TEAL,"bold")
    c.txt((1240,24),"A SYSTEMATIC REVIEW NIGHT OUT",13,MUTED,"bold","rt")
    c.line([(42,53),(1240,53)],"#29324b")
    c.txt((42,70),f"0{scene+1}  /  {TIMELINE['scenes'][scene]['title'].upper()}",13,PINK,"bold")
    c.txt((1240,70),f"{int(t)//60}:{int(t)%60:02d} / 3:45",13,MUTED,"mono","rt")


def scene_open(c,u,t):
    c.txt((45,113),"JUST A QUICK REVIEW.",47,WHITE,"bold")
    c.txt((47,177),"A reasonable request. An unreasonable guest list.",24,MUTED)
    # Club facade and doorway.
    c.box((507,258,955,560),"#161c33", "#36415f", 8)
    c.box((575,329,783,560),"#050b19", "#6d4671", 8, 2)
    c.box((553,281,808,321),INK,PINK,6,2)
    c.txt((680,290),"ELIGIBILITY",24,PINK,"bold","mt")
    c.txt((679,345),"HUMAN SCREENING",13,TEAL,"bold","mt")
    c.txt((679,369),"FULL TEXT UPSTAIRS",11,MUTED,"bold","mt")
    c.line([(842,465),(927,357)],"#6b7998",3)
    for yy in range(365,484,19):
        c.line([(842,yy+17),(923,yy+17)],"#38435f",2)
    librarian(c,823,554,1.15,t)
    for i in range(9):
        xx = 25+i*66+(u*5)%40
        yy = 445 + (i%2)*27
        paper(c,xx,yy,t+i,.87,BLUE if i%3 else PINK)
    # Velvet rope, foreground.
    for xx in [65,230,399,568]:
        c.ellipse((xx-7,508,xx+7,522),GOLD)
        c.line([(xx,517),(xx,563)],"#7d6d65",5)
        c.ellipse((xx-19,559,xx+19,566),"#7d6d65")
    c.line([(65,519),(150,537),(230,519),(314,537),(399,519),(483,537),(568,519)],PINK,5)
    c.box((995,267,1233,385),PANEL,"#34425f",10)
    c.txt((1015,285),"COAT CHECK",14,GOLD,"bold")
    c.txt((1015,312),"Deduplication",22,WHITE,"bold")
    c.txt((1015,347),"Missing: Supplementary Appendix",11,MUTED,maxwidth=198)
    if u>8:
        c.box((992,406,1233,529),"#26223b",PINK,10)
        c.pill(1008,419,"MESSAGE FROM THE PI",PINK,11)
        c.paragraph((1009,456),"Just a quick review. Shouldn't take long.",20,WHITE,199)
    c.pill(48,238,"26,832 ABSTRACT-AVAILABLE RECORDS",BLUE,13)


def scene_talent(c,u,t):
    c.txt((45,113),"THE TALENT HAS ARRIVED.",45,WHITE,"bold")
    c.txt((47,176),"One decision. Several billable paragraphs.",24,MUTED)
    # Limousine, slight arrival movement.
    offset=-210*(1-smooth(u/3))
    c.box((45+offset,397,448+offset,475),"#26213e",PINK,18,2)
    c.poly([(105+offset,399),(145+offset,358),(345+offset,358),(393+offset,399)],"#33274b")
    c.box((149+offset,366,242+offset,396),"#7082aa",radius=3)
    c.box((251+offset,366,341+offset,396),"#7082aa",radius=3)
    for xx in [122,364]:
        c.ellipse((xx-27+offset,448,xx+27+offset,502),INK,"#75859f",3)
        c.ellipse((xx-11+offset,464,xx+11+offset,486),"#465370")
    llm(c,537,559,t,1.28)
    librarian(c,967,559,1.15,t)
    c.box((688,339,831,536),"#efe4ce",radius=4)
    c.txt((759,355),"TOKEN RECEIPT",12,INK,"bold","mt")
    for i in range(7):
        c.line([(707,389+i*17),(811,389+i*17)],"#a89c89",1)
    c.txt((759,514),"CONTINUED…",10,INK,"mono","mt")
    c.box((813,510,890,556),"#efe4ce",radius=4)
    c.line([(834,523),(875,523)],"#a89c89")
    if 8<u<18:
        c.box((371,227,936,310),PANEL,PINK,12)
        c.paragraph((390,245),"Before deciding, we must consider the epistemological status of relevance…",23,WHITE,520)
    if u>=23:
        robot(c,1147,559,t,1.2)
        c.pill(1034,362,"NO ENTOURAGE",TEAL,12)
    else:
        c.pill(1044,331,"STAFF WI-FI",GOLD,12)
        c.txt((1044,373),"final_FINAL_",15,MUTED,"mono")
        c.txt((1044,396),"search_v7",15,MUTED,"mono")


def scene_receipt(c,u,t):
    if u<12.8:
        c.txt((45,113),"A VERY SMALL BOUNCER.",46,WHITE,"bold")
        c.txt((47,177),"Zero-shot classification. Structured output.",24,MUTED)
        c.box((45,250,355,459),PANEL,"#34425f",12)
        c.txt((68,274),"SUPPLIED CRITERIA",15,PINK,"bold")
        c.paragraph((68,311),"Should this record be retained for human screening?",28,WHITE,259,"bold")
        paper(c,288,476,t,1.05)
        c.arrow((374,365),(526,365))
        robot(c,637,490,t,2.0,True)
        c.arrow((859,365),(945,365))
        c.box((967,259,1232,458),PANEL,TEAL,12)
        c.txt((989,280),"HUMAN SCREENING",16,TEAL,"bold")
        c.paragraph((989,321),"Rank the queue. Check the papers.",32,WHITE,222,"bold")
        c.pill(967,485,"JEV DOESN'T WRITE MONOLOGUES",TEAL,11,width=265)
        return
    c.txt((45,113),"SMALL MODEL. TINY RECEIPT.",44,WHITE,"bold")
    c.txt((47,174),"Reported retrospective benchmark results",23,MUTED)
    c.box((44,222,791,552),PANEL,"#34425f",14)
    c.txt((68,241),"MEAN WSS@95",16,TEAL,"bold")
    c.txt((64,269),"0.661",99,TEAL,"bold")
    c.txt((373,288),"8 DTA reviews",27,WHITE,"bold")
    c.txt((373,332),"26,832 records with abstracts",19,MUTED)
    c.txt((68,401),"ACTUAL REVIEW-LEVEL VARIATION",12,MUTED,"bold")
    for i,r in enumerate(REVIEWS):
        x=75+i*86
        val=float(r["WSS@95"])
        h=91*val
        color=GOLD if val<.3 else TEAL
        c.box((x,444,x+53,532),"#1c2942",radius=4)
        c.box((x,532-h,x+53,532),color,radius=4)
        c.txt((x+26,433),f"{val:.3f}",12,color,"mono","mt")
        c.txt((x+26,536),r["review_id"][-3:],11,MUTED,"mono","mt")
    c.box((842,229,1208,422),"#f0e8d7",radius=9)
    c.txt((867,252),"REPORTED RUN COST",14,INK,"bold")
    c.txt((863,286),"≈ US$1.46",53,INK,"bold",maxwidth=319)
    c.txt((867,366),"Procurement may now exhale.",16,"#65596b")
    robot(c,937,562,t,1.05)
    librarian(c,1137,562,1.05,t)
    if u>22:
        c.pill(45,568,"WSS@95: WORK SAVED OVER SAMPLING AT 95% RECALL",TEAL,13,width=747)


def scene_ensemble(c,u,t):
    c.txt((45,113),"THE VIPS DO SCORE HIGHER.",44,WHITE,"bold")
    c.txt((47,174),"Reported retrospective benchmark results • higher WSS@95 is better",21,MUTED)
    c.box((44,223,770,539),PANEL,"#34425f",13)
    vals=[("Jev • one question",.661,TEAL),("Three-model ensemble",.680,PINK),("Ensemble + embedding reranking",.708,GOLD)]
    for i,(label,val,color) in enumerate(vals):
        yy=253+i*93
        c.txt((67,yy),label,19,WHITE,"bold")
        c.box((68,yy+34,641,yy+54),"#202a43",radius=5)
        p=smooth((u-i*.8-1)/2)
        c.box((68,yy+34,68+val/.8*573*p,yy+54),color,radius=5)
        c.txt((737,yy+25),f"{val:.3f}",27,color,"bold","rt")
    for i,(name,col) in enumerate([("GPT",PINK),("GEMINI",BLUE),("CLAUDE",GOLD)]):
        llm(c,875+i*128,514,t+i,.72,col,name)
        c.box((829+i*128,519,922+i*128,559),"#252239",col,5)
    c.pill(816,240,"THE ENSEMBLE",PINK,13,width=394)
    c.txt((1013,287),"3 MODELS",30,WHITE,"bold","mt")
    c.txt((1013,330),"1 DECISION",24,MUTED,"bold","mt")
    c.pill(45,557,"PUBLISHED COMPARISONS • OLDER MODELS • RESULTS MAY CHANGE",GOLD,13,width=725)


def scene_forms(c,u,t):
    c.txt((45,113),"MANAGEMENT HAS A DIAGRAM.",43,WHITE,"bold")
    c.txt((47,176),"The tested five-question workflow",24,MUTED)
    # Five questionnaires and a unnecessarily complex conveyor.
    c.box((47,296,706,523),"#121c31","#34425f",12)
    for i in range(5):
        x=108+i*121
        paper(c,x,358,t+i,1.25,PINK,label=f"Q{i+1}",worried=True)
        c.line([(x,423),(x,460)],"#8598b7",2)
        c.ellipse((x-6,454,x+6,466),PINK)
    c.line([(76,470),(678,470)],"#8598b7",10)
    for i in range(12):
        xx=80+i*50
        c.ellipse((xx-8,465,xx+8,481),"#293954",TEAL,1)
        ang=t*2
        c.line([(xx,473),(xx+6*math.sin(ang),473+6*math.cos(ang))],TEAL,1)
    c.arrow((706,463),(789,463),PINK)
    c.box((803,230,1226,541),PANEL,PINK,13)
    c.txt((826,255),"EXPECTED-SCORE VARIANT",16,PINK,"bold")
    c.txt((825,293),"0.536",87,PINK,"bold")
    c.txt((829,412),"vs 0.661 for one question",24,WHITE,"bold")
    c.txt((829,455),"Mean WSS@95 • this tested setup",18,MUTED)
    c.pill(47,236,"WORKFLOW OPTIMISATION COMMITTEE",PINK,13,width=659)
    c.pill(47,545,"5 × THE JUDGEMENTS",GOLD,14,width=274)
    c.pill(346,545,"WHY? QUESTIONS / SCORING = HYPOTHESES",BLUE,12,width=361)
    if u>22:
        librarian(c,742,556,1.02,t)


def scene_question(c,u,t):
    if u<8.2:
        # The joke lands against a suddenly empty room.
        c.txt((45,113),"ONE QUESTION.",48,WHITE,"bold")
        c.txt((52,253),"How do you know",60,WHITE,"bold")
        c.txt((52,326),"when to stop screening?",57,PINK,"bold",maxwidth=965)
        librarian(c,1134,554,1.6,t)
        return
    if u<31.5:
        c.txt((45,113),"THE ORACLE HAS ENTERED.",44,WHITE,"bold")
        c.txt((47,175),"Known labels locate the recall target after scoring.",24,MUTED)
        c.ellipse((81,244,392,555),"#153e50",TEAL,3)
        c.ellipse((103,266,372,533),"#1e465c",BLUE,2)
        c.ellipse((128,287,184,343),"#628da1")
        for i in range(9):
            xx=225+88*math.sin(t*.4+i*1.9)
            yy=391+84*math.cos(t*.4+i*1.9)
            c.ellipse((xx-2,yy-2,xx+2,yy+2),GOLD)
        c.txt((238,360),"KNOWN",27,GOLD,"bold","mt")
        c.txt((238,397),"BENCHMARK LABELS",18,GOLD,"bold","mt")
        c.box((111,542,365,566),"#635060",radius=6)
        c.pill(143,225,"EVALUATOR'S CRYSTAL BALL",TEAL,11)
        c.arrow((416,393),(530,393),GOLD)
        c.box((552,261,970,449),PANEL,GOLD,13)
        c.txt((577,284),"RETROSPECTIVE EVALUATION",15,GOLD,"bold")
        c.paragraph((577,329),"Find the 95% recall point in the scored ranking.",32,WHITE,363,"bold")
        c.pill(552,475,"LABELS USED ONLY AFTER SCORING",TEAL,13,width=418)
        librarian(c,1125,560,1.18,t)
        c.txt((75,582),"Hindsight can measure a result. A new review needs a validated stopping rule.",17,MUTED)
        return
    if u<43.7:
        c.txt((45,113),"PROSPECTIVE VALIDATION.",45,WHITE,"bold")
        c.txt((47,175),"The work behind an automated exclusion policy",24,MUTED)
        items=[("01","THRESHOLDS","Choose and test them before the new review."),("02","CALIBRATION","Check whether probabilities match outcomes."),("03","STOPPING RULES","Validate when screening can stop.")]
        for i,(num,title,body) in enumerate(items):
            yy=244+i*104
            c.box((48,yy,947,yy+85),PANEL,"#36445f",10)
            c.txt((70,yy+22),num,29,TEAL,"bold")
            c.txt((140,yy+14),title,21,WHITE,"bold")
            c.txt((140,yy+48),body,20,MUTED)
        robot(c,1114,561,t,1.15)
        c.pill(48,566,"8 DTA REVIEWS ≠ EVERY REVIEW TYPE",GOLD,14,width=899)
        return
    if u<58:
        c.txt((45,113),"SOME THINGS NEVER CHANGE.",43,WHITE,"bold")
        c.txt((47,176),"Full text is still upstairs.",24,MUTED)
        c.box((55,253,752,359),PANEL,BLUE,12)
        c.paragraph((78,276),"The methods are in the full text.",36,WHITE,650,"bold")
        paper(c,285,486,t,1.8,BLUE)
        librarian(c,959,558,1.45,t)
        # The PRISMA-weekends Easter egg.
        c.box((466,424,712,469),PANEL,"#65728c",6)
        c.txt((589,432),"WEEKENDS IDENTIFIED: 12",11,MUTED,"bold","mt")
        c.arrow((589,470),(589,499),MUTED,2)
        c.box((466,504,712,549),PANEL,PINK,6)
        c.txt((589,514),"WEEKENDS REMAINING: 0",11,PINK,"bold","mt")
        c.txt((589,402),"PERSONAL PRISMA DIAGRAM",11,MUTED,"bold","mt")
        return
    c.txt((48,134),"CHEAP DECISIONS.",67,TEAL,"bold")
    c.txt((48,221),"EXPENSIVE QUESTIONS.",59,WHITE,"bold",maxwidth=1150)
    c.txt((52,320),"Jev works the queue. The librarian keeps the keys.",27,MUTED)
    librarian(c,960,554,1.16,t,"keys")
    robot(c,1151,554,t,1.1)
    c.box((48,407,782,516),PANEL,"#34425f",10)
    c.txt((70,426),"BASED ON AARON TAY'S ARTICLE",14,PINK,"bold")
    c.txt((70,456),"Can Jev compete with LLMs for systematic review screening?",22,WHITE,"bold",maxwidth=686)
    c.txt((70,490),"1 October 2026  •  aarontay.substack.com",15,MUTED)


SCENE_DRAW=[scene_open,scene_talent,scene_receipt,scene_ensemble,scene_forms,scene_question]
CAPTIONS=[]


def draw_frame(t, captions=True):
    im=BG.copy()
    c=Canvas(im)
    scene=next((i for i,s in enumerate(TIMELINE["scenes"]) if s["start"]<=t<s["end"]),5)
    u=t-TIMELINE["scenes"][scene]["start"]
    chrome(c,scene,t)
    SCENE_DRAW[scene](c,u,t)
    # A quiet progress line also makes chapter changes perceptible.
    c.box((0,713,1280,720),"#131a2e")
    c.box((0,713,1280*clamp(t/DURATION),720),TEAL)
    if captions:
        cap=next((a for a in CAPTIONS if a["start"]<=t<a["end"]),None)
        if cap:
            c.box((30,607,1250,704),"#080c19", "#28344e",10)
            speakercolor=GOLD if cap["speaker"]=="Librarian" else PINK if cap["speaker"] in ["LLM","PI"] else TEAL
            c.txt((50,617),cap["speaker"].upper(),11,speakercolor,"bold")
            lines=wrap_words(cap["text"],27,1160)
            assert len(lines)<=2, cap
            for j,line in enumerate(lines):
                c.txt((640,641+j*31),line,27,WHITE,"normal","mt")
    # Brief, restrained fades at chapter boundaries.
    if t<.7:
        im=Image.blend(Image.new("RGB",im.size,INK),im,smooth(t/.7))
    return im


def ffmpeg_exe():
    import imageio_ffmpeg
    return imageio_ffmpeg.get_ffmpeg_exe()


def read_wave(path):
    with wave.open(str(path)) as f:
        assert f.getsampwidth()==2
        data=np.frombuffer(f.readframes(f.getnframes()),dtype=np.int16).astype(np.float32)/32768
        if f.getnchannels()>1:
            data=data.reshape(-1,f.getnchannels()).mean(axis=1)
        rate=f.getframerate()
        if rate!=SR:
            points=np.arange(round(len(data)*SR/rate),dtype=np.float64)*rate/SR
            data=np.interp(points,np.arange(len(data)),data).astype(np.float32)
    return data


def write_wave(path,data):
    data=np.clip(data,-1,1)
    with wave.open(str(path),"wb") as f:
        f.setnchannels(2 if data.ndim==2 else 1)
        f.setsampwidth(2)
        f.setframerate(SR)
        f.writeframes((data*32767).astype(np.int16).tobytes())


def split_caption(text,limit=86):
    # Sentence-aware: a punchline is not revealed a caption early.
    sentences=re.split(r"(?<=[.!?])\s+",text)
    chunks=[]
    for sentence in sentences:
        if len(sentence)<=limit:
            chunks.append(sentence)
        else:
            chunks.extend(textwrap.wrap(sentence,limit,break_long_words=False,break_on_hyphens=False))
    return chunks


def subtitle_time(t,srt=False):
    ms=round(t*1000)
    hh,ms=divmod(ms,3600000)
    mm,ms=divmod(ms,60000)
    ss,ms=divmod(ms,1000)
    return f"{hh:02}:{mm:02}:{ss:02}{',' if srt else '.'}{ms:03}"


def load_captions():
    global CAPTIONS
    CAPTIONS=json.loads((OUT/"captions.json").read_text(encoding="utf-8"))


def prepare_audio():
    global CAPTIONS
    count=int(DURATION*SR)
    speech=np.zeros(count,dtype=np.float32)
    duck=np.ones(count,dtype=np.float32)
    CAPTIONS=[]
    timings=[]
    ffmpeg=ffmpeg_exe()
    for i,cue in enumerate(TIMELINE["cues"]):
        data=read_wave(BASE/"audio"/f"{i:02}.wav")
        loud=np.flatnonzero(np.abs(data)>.004)
        if not len(loud):
            raise ValueError(f"Silent voice clip {i}")
        trim_start=max(0,loud[0]-int(.06*SR))
        data=data[trim_start:min(len(data),loud[-1]+int(.12*SR))]
        word_times=json.loads((BASE/"audio"/f"{i:02}.json").read_text(encoding="utf-8-sig"))
        if isinstance(word_times,dict):
            word_times=[word_times]
        assert word_times, f"No speech timing events for {i}"
        slot=cue["end"]-cue["start"]-.08
        original_duration=len(data)/SR
        tempo=max(1,original_duration/slot)
        if tempo>1:
            result=subprocess.run([ffmpeg,"-hide_banner","-loglevel","error","-f","f32le","-ar",str(SR),"-ac","1","-i","pipe:0","-af",f"atempo={tempo:.6f}","-f","f32le","pipe:1"],input=data.astype(np.float32).tobytes(),capture_output=True,check=True)
            data=np.frombuffer(result.stdout,dtype=np.float32).copy()
        if len(data)>round(slot*SR):
            data=data[:round(slot*SR)]
        data*=.79/(np.max(np.abs(data))+1e-9)
        start=round(cue["start"]*SR)
        speech[start:start+len(data)]+=data
        actual_end=cue["start"]+len(data)/SR
        duck[max(0,start-int(.08*SR)):min(count,start+len(data)+int(.22*SR))]=.24
        chunks=split_caption(cue["text"])
        starts=[]
        char_cursor=0
        for text in chunks:
            pos=cue["text"].find(text,char_cursor)
            assert pos>=0, (text,cue)
            char_cursor=pos+len(text)
            event=next(w for w in word_times if w["Position"]>=pos)
            relative=max(0,event["Seconds"]-trim_start/SR)/tempo
            starts.append(cue["start"]+relative)
        for j,text in enumerate(chunks):
            end=starts[j+1] if j+1<len(starts) else actual_end
            assert cue["start"]<=starts[j]<end<=actual_end+.003, (i,text,starts[j],end,actual_end)
            CAPTIONS.append({"start":round(starts[j],3),"end":round(end,3),"speaker":cue["speaker"],"text":text})
        timings.append({"cue":i,"speaker":cue["speaker"],"start":cue["start"],"end":round(actual_end,3),"original_seconds":round(original_duration,3),"tempo":round(tempo,3)})
    # Original restrained nightclub bed. All notes and percussion are synthesized.
    music=np.zeros(count,dtype=np.float32)
    beat=60/104
    rng=np.random.default_rng(46)
    chords=[[130.81,155.56,196.0],[103.83,130.81,155.56],[116.54,146.83,174.61],[98,123.47,146.83]]
    for b in range(math.ceil(DURATION/beat)):
        now=b*beat
        if 159.8<now<217.8:
            continue
        start=int(now*SR)
        if start>=count:
            continue
        kt=np.arange(int(.19*SR))/SR
        kick=np.sin(2*np.pi*(43*kt+4*(1-np.exp(-kt*22))))*np.exp(-kt*23)*.043
        n=min(len(kick),count-start)
        music[start:start+n]+=kick[:n]
        ht=np.arange(int(.055*SR))/SR
        hat=rng.normal(0,1,len(ht))*np.exp(-ht*85)*.006
        start2=start+int(beat*.5*SR)
        if start2<count:
            n=min(len(hat),count-start2)
            music[start2:start2+n]+=hat[:n]
        if b%2==0:
            nt=np.arange(int(beat*1.8*SR))/SR
            freqs=chords[(b//8)%4]
            notes=sum(np.sin(2*np.pi*f*nt)+.20*np.sin(4*np.pi*f*nt) for f in freqs)
            notes=notes*np.minimum(nt*80,1)*np.exp(-nt*2.5)*.006
            n=min(len(notes),count-start)
            music[start:start+n]+=notes[:n]
    # Silence is deliberate: the stopping-rule question arrives without a beat.
    music[int(159.8*SR):int(217.8*SR)]=0
    for sec,frequency in [(68.8,622.25),(83.7,830.61),(96,523.25),(96.25,659.25),(96.5,783.99),(138.2,196)]:
        st=int(sec*SR)
        nt=np.arange(int(.35*SR))/SR
        chime=np.sin(2*np.pi*frequency*nt)*np.exp(-nt*10)*.038
        music[st:st+len(chime)]+=chime
    # Music begins and ends smoothly, and sits below the words.
    fade=min(int(1.2*SR),count)
    music[:fade]*=np.linspace(0,1,fade)
    music[-fade:]*=np.linspace(1,0,fade)
    music*=duck
    stereo=np.column_stack([music+speech,music*.96+speech])
    peak=float(np.max(np.abs(stereo)))
    if peak>.94:
        stereo*=.94/peak
    write_wave(OUT/"master_audio.wav",stereo)
    write_wave(OUT/"voiceover.wav",speech)
    (OUT/"captions.json").write_text(json.dumps(CAPTIONS,indent=2),encoding="utf-8")
    (OUT/"voice_timings.json").write_text(json.dumps(timings,indent=2),encoding="utf-8")
    srt=[]
    vtt=["WEBVTT","", "NOTE Captions are also burned into the supplied MP4.", ""]
    for i,cap in enumerate(CAPTIONS):
        body="\n".join(textwrap.wrap(cap["text"],64,break_long_words=False,break_on_hyphens=False))
        speaker=cap["speaker"].upper()+": "
        srt.extend([str(i+1),f"{subtitle_time(cap['start'],True)} --> {subtitle_time(cap['end'],True)}",speaker+body,""])
        vtt.extend([f"{subtitle_time(cap['start'])} --> {subtitle_time(cap['end'])}",speaker+body,""])
    (OUT/"club_eligibility.srt").write_text("\n".join(srt),encoding="utf-8")
    (OUT/"club_eligibility.vtt").write_text("\n".join(vtt),encoding="utf-8")
    max_tempo=max(t["tempo"] for t in timings)
    print(f"Audio ready: {len(TIMELINE['cues'])} voice clips, {len(CAPTIONS)} captions; maximum timing adjustment {max_tempo:.3f}x.",flush=True)


def write_script():
    lines=["# Club Eligibility: The $1.46 Bouncer","","3:45 animated explainer • 445 spoken words • conference-safe satire","","Source: [Aaron Tay, 1 October 2026]("+TIMELINE["source"]+")","","Jev has no spoken dialogue. The soundtrack is original synthesized music; character voices use local Windows speech synthesis.",""]
    for scene in TIMELINE["scenes"]:
        lines.extend(["## "+subtitle_time(scene["start"])[3:8]+" — "+scene["title"],""])
        for cue in TIMELINE["cues"]:
            if scene["start"]<=cue["start"]<scene["end"]:
                lines.extend([f"**{subtitle_time(cue['start'])[3:8]} · {cue['speaker']}**",cue["text"],""])
    lines.extend(["## Fact and interpretation notes","","- 0.661 is the unweighted mean of eight revised review-level WSS@95 values; it is not pooled accuracy or a validated prospective saving.","- The main benchmark contains 26,832 review-record pairs with abstracts and 423 relevant labels. The bar chart uses the revised September 30 run, not the earlier README baseline.","- The article reports approximately US$1.46. The receipt is labelled as a reported run cost, not a tariff or an all-inclusive price for a live review.","- Ensemble scores 0.680 and 0.708 are published benchmark comparisons reported in the article; the cartoon does not imply a newly controlled head-to-head experiment.","- 0.536 refers to the Jev-QA-Expected variant (0.5358 rounded), not the hard-answer variant. Possible causes are explicitly hypotheses.","- Gold labels are evaluation-only. The oracle scene depicts the evaluator consulting labels after scoring, never supplying labels to Jev.","- The classification output p(retain) = 0.87 is illustrative. Calibration on this task has not been established.","- Thresholds, calibration, stopping rules, and generalization require further prospective validation.",""])
    (OUT/"script.md").write_text("\n".join(lines),encoding="utf-8")
    manifest={"title":TIMELINE["title"],"duration_seconds":225,"fps":FPS,"width":WIDTH,"height":HEIGHT,"spoken_words":sum(len(c["text"].split()) for c in TIMELINE["cues"]),"source_article":TIMELINE["source"],"revised_bar_source":"outputs/dta_structured_state_2026-09-30/abstract_filter_metrics.csv; dataset=rerun_abstract_available","review_bars":[{"review_id":r["review_id"],"n":int(r["total_records"]),"wss95":float(r["WSS@95"])} for r in REVIEWS],"voice_engine":"Windows System.Speech; locally installed voices","music":"Original synthesized score; no external music samples","subtitles":"Burned into MP4; matching SRT and VTT also supplied"}
    (OUT/"production_manifest.json").write_text(json.dumps(manifest,indent=2),encoding="utf-8")


def previews():
    times=[4,18,37,52,60,76,86,104,132,149,164,175,198,213,221]
    tiles=[]
    for t in times:
        im=draw_frame(t)
        im.save(OUT/f"frame_{t:03}.png")
        tile=im.resize((640,360),Image.Resampling.LANCZOS)
        tiles.append(tile)
    sheet=Image.new("RGB",(640*3,390*5),INK)
    for i,(tile,t) in enumerate(zip(tiles,times)):
        x=(i%3)*640
        y=(i//3)*390
        sheet.paste(tile,(x,y+30))
        d=ImageDraw.Draw(sheet)
        d.text((x+12,y+5),f"{int(t)//60}:{int(t)%60:02d}",font=ImageFont.truetype(str(FONTROOT/"segoeuib.ttf"),17),fill=TEAL)
    sheet.save(OUT/"storyboard.png")
    poster=draw_frame(221,captions=False)
    poster.save(OUT/"poster.png")
    print("Poster and 15 review frames ready.",flush=True)


def render():
    output=OUT/"club_eligibility.mp4"
    cmd=[ffmpeg_exe(),"-hide_banner","-loglevel","warning","-y","-f","rawvideo","-pixel_format","rgb24","-video_size",f"{WIDTH}x{HEIGHT}","-framerate",str(FPS),"-i","pipe:0","-i",str(OUT/"master_audio.wav"),"-map","0:v:0","-map","1:a:0","-c:v","libx264","-preset","fast","-crf","20","-threads","4","-pix_fmt","yuv420p","-c:a","aac","-b:a","192k","-ar",str(SR),"-t",str(DURATION),"-movflags","+faststart","-metadata","title="+TIMELINE["title"],"-metadata","comment=Original animated satire based on Aaron Tay's article, 1 October 2026.",str(output)]
    with (OUT/"render.log").open("wb") as log:
        p=subprocess.Popen(cmd,stdin=subprocess.PIPE,stdout=subprocess.DEVNULL,stderr=log)
        try:
            for i in range(DURATION*FPS):
                im=draw_frame(i/FPS)
                p.stdin.write(im.tobytes())
                if i%(FPS*10)==0:
                    print(f"Rendered {i//FPS:03d} / {DURATION} seconds",flush=True)
            p.stdin.close()
            status=p.wait()
            if status:
                raise RuntimeError((OUT/"render.log").read_text(errors="replace"))
        except Exception:
            p.kill()
            p.wait()
            raise
    print(f"Video ready: {output} ({output.stat().st_size/1048576:.1f} MiB)",flush=True)


def validate():
    manifest=json.loads((OUT/"production_manifest.json").read_text(encoding="utf-8"))
    timings=json.loads((OUT/"voice_timings.json").read_text(encoding="utf-8"))
    for a,b in zip(TIMELINE["cues"],TIMELINE["cues"][1:]):
        assert a["end"]<=b["start"], (a,b)
    for timing,cue in zip(timings,TIMELINE["cues"]):
        assert timing["end"]<=cue["end"]+.02
        assert timing["tempo"]<1.35, timing
    for a,b in zip(CAPTIONS,CAPTIONS[1:]):
        assert a["end"]<=b["start"]+.002
    for cap in CAPTIONS:
        assert 0<=cap["start"]<cap["end"]<=DURATION
        cue=next(c for c in TIMELINE["cues"] if c["speaker"]==cap["speaker"] and c["start"]<=cap["start"]<c["end"])
        assert cap["end"]<=cue["end"]+.002
    assert all(len(wrap_words(cap["text"],27,1160))<=2 for cap in CAPTIONS)
    assert not any(cue["speaker"].lower()=="jev" for cue in TIMELINE["cues"])
    assert manifest["spoken_words"]==445
    with wave.open(str(OUT/"master_audio.wav")) as w:
        assert w.getnframes()/w.getframerate()==225
        assert w.getnchannels()==2
    output=OUT/"club_eligibility.mp4"
    if output.exists():
        result=subprocess.run([ffmpeg_exe(),"-hide_banner","-i",str(output),"-map","0:v:0","-map","0:a:0","-f","null","-"],capture_output=True,text=True)
        assert result.returncode==0,result.stderr
        assert "Duration: 00:03:45.00" in result.stderr,result.stderr[:1200]
        assert "1920x1080" in result.stderr
        (OUT/"decode_check.log").write_text(result.stderr,encoding="utf-8")
        print("Verified: full video/audio decode, 225 seconds, 1920×1080, readable caption widths, no voice overlaps, revised benchmark mean.",flush=True)
    else:
        print("Pre-render checks passed.",flush=True)


if __name__=="__main__":
    parser=argparse.ArgumentParser()
    parser.add_argument("--prepare",action="store_true")
    parser.add_argument("--preview",action="store_true")
    parser.add_argument("--render",action="store_true")
    parser.add_argument("--validate",action="store_true")
    args=parser.parse_args()
    if args.prepare:
        prepare_audio()
        write_script()
    else:
        load_captions()
    if args.preview:
        previews()
    if args.validate:
        validate()
    if args.render:
        render()
